vich_uploader:
    db_driver: orm # sau mongodb sau propach, în funcție de ce utilizezi
    mappings:
        product_images:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/product/new'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
            delete_on_remove: true
            delete_on_update: true
