<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
    'category' => [['category'], ['_controller' => 'App\\Controller\\DefaultController::category'], [], [['variable', '/', '[^/]++', 'category'], ['text', '/category']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
