<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOg1HGxA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOg1HGxA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOg1HGxA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOg1HGxA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOg1HGxA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Og1HGxA',
    'container.build_id' => '1f996b64',
    'container.build_time' => 1720866497,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOg1HGxA');
